[package]
name = "investment_contract_finallyy"
version = "13.0.0"

[addresses]
investment_contract_finallyy = "0x51e1de64d24251bbd3d9d96914e9cb8e79e08b3396c66c974d4b6087c0273916"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "918b643c98f81b8b2b3dd3a597329210b35c30b3" }